# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Install necessary packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends mariadb-client \
    && apt-get install -y --no-install-recommends gcc libc-dev python3-dev libffi-dev \
    && apt-get install -y --no-install-recommends curl \
    && apt-get install -y --no-install-recommends bash \
    && apt-get install -y --no-install-recommends openrc \
    && apt-get install -y --no-install-recommends build-essential 

# Clean up
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container to /app
WORKDIR /app

# Copy application files
COPY app/ ./app
COPY core/ ./core
COPY migrations/ ./migrations
COPY rosemary/ ./rosemary
COPY setup.py ./

# Copy requirements.txt into the working directory
COPY requirements.txt .

# Removes cache at the build stage
RUN find . -type d -name "__pycache__" -exec rm -r {} + && \
    find . -type f -name "*.pyc" -exec rm -f {} +

# Update pip
RUN pip install --no-cache-dir --upgrade pip

# Install application dependencies
RUN pip install -r requirements.txt

# Install rosemary as an editable package
RUN pip install -e ./ && echo "Rosemary installed successfully"

# Expose port 80
EXPOSE 80

# Copy and set entrypoint
COPY docker/entrypoints/development_render_entrypoint.sh /app/development_render_entrypoint.sh
RUN chmod +x /app/render_entrypoint.sh

# Copy the wait-for-db.sh script and set execution permissions
COPY scripts/wait-for-db.sh /app/scripts/wait-for-db.sh
RUN chmod +x /app/scripts/wait-for-db.sh

# Command to run the application
CMD ["./development_render_entrypoint.sh"]
